swagger: "2.0"
   
definitions: 
  
 # Définition de l'objet ${rootAggregate}
 ${rootAggregate}:
  type: object
  properties:
    # Id technique
    id:
      type: string
      format: UUID
    # firstName du ${rootAggregate} (For demo only)
    firstName:
      type: string
    # lastName du ${rootAggregate} (For demo only)
    lastName:
      type: string
    # birthDate du ${rootAggregate} (For demo only)
    birthDate:
      type: string